name: dart_websocket_nats
version: 0.1.0
description: NATS client for Dart language, use WebSocket proxy NATS message
author: Linfulong <1126101262@qq.com>
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  test: any
  mockito: any
  web_socket_channel: ^2.0.0
  logging: ^1.0.1
